[package]
name = "cargo-casper"
version = "2.2.1"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2021"
description = "A command line tool for creating a Wasm smart contract and tests for use on the Casper network."
documentation = "https://docs.rs/cargo-casper"
readme = "README.md"
homepage = "https://casperlabs.io"
repository = "https://github.com/casper-ecosystem/cargo-casper"
license = "Apache-2.0"
include = ["src/*.rs", "Cargo.lock", "Cargo.toml", "resources/*"]

[dependencies]
clap = { version = "=4.5.7", features = ["cargo", "wrap_help"] }
colour = "2.1"
once_cell = "1.19"

[dev-dependencies]
assert_cmd = "2.0"
reqwest = { version = "0.12", features = ["blocking"] }
serde_json = "1.0"
tempfile = "3.10"
