---
name: ci-cargo-casper

on:
  push:
    branches:
      - "dev"
      - "feat-*"
      - "release-*"
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - "dev"
      - "feat-*"
      - "release-*"
    paths-ignore:
      - '**.md'

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Get nightly toolchain from file
        id: nightly-toolchain
        run: echo "version=$(cat resources/rust-toolchain.in)" >> $GITHUB_OUTPUT

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.nightly-toolchain.outputs.version }}
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: fmt -- --check

      - name: Audit
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: audit

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: clippy --all-targets

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: test
